### ISSUE TITLE
"Invalid Answers" Even Tho Correct Answers Were Chosen

### ISSUE THREAD

**Issue by 5S6** [xtekky/Hcaptcha-solver#3]
This is probably just a me problem I'm having and maybe I'm doing something wrong, but everytime it always results in "Invalid Answers" even though the correct images are chosen. Is it me or possibly something with the code? I'll leave a ss down below if that helps at all.  Sorry if it's just me having this problem, and thanks :D   
<img width="1108" alt="Screen Shot 2022-07-22 at 3 10 25 PM" src="https://user-images.githubusercontent.com/71937946/180507677-df771fb7-b93b-41d9-8445-1e9f742a464b.png">

**Comment by 5S6** [comment]
I honestly may just be dumb and am missing something pretty obvious 😭

**Comment by xtekky** [comment]
Its prolly the code, but I will not fix it in a while you can take this repo as a base for your project
